name: domain
version: 0.0.1
publish_to: none
description: Project domain module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
