name: settings
description: Settings feature
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  navigation:
    path: ../../navigation

  equatable: ^2.0.7
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8